export {default as App} from "./app/app"
export {default as Main} from "./main/main"
export {default as Navbar} from "./navbar/navbar"
export {default as Footer} from "./footer/footer"
export {default as Menu} from "./menu/menu"
export {default as About} from "./about/about"